### ISSUE TITLE
hello~

### ISSUE THREAD

**Issue by Justjustifyjudge** [cilinmengye/cilinmengye#1]
摸鱼时在wiki上看到了经验贴，发现是同保浙软的同学（握爪）

**Comment by cilinmengye** [comment]
佬好，希望有机会能够在浙软见面。

![bcebe872b216f1bad7cba1276d7e8ebd](https://github.com/user-attachments/assets/299d96ef-9544-4909-b7b6-b9a1bd73ecee)
